### ISSUE TITLE
Add Support for megane/HWYLA/WAILA-type mods

### ISSUE THREAD

**Issue by EnigmaticaGH** [skylorbeck/tokenablefurnaces#9]
Currently the tokenable inventories cannot be inspected because they lack an "inventory" tag according to the logs below. Is it possible to fix this bug / add an enhancement to support mods that display inventory contents?

```
[14:47:20] [Server thread/ERROR]: Something went wrong when retrieving data for website.skylorbeck.minecraft.tokenablefurnaces.chests.GoldChestEntity at (-218, 96, -475)
[14:47:20] [Server thread/ERROR]: Stacktrace:
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1263.method_5439()" because "this.inventory" is null
	at lol.bai.megane.api.provider.base.InventoryItemProvider.getSlotCount(InventoryItemProvider.java:33) ~[megane-api-7.0.0-2907d68cd2cd1a21.jar:?]
	at lol.bai.megane.runtime.data.block.BlockInventoryData.append(BlockInventoryData.java:38) ~[megane-runtime-7.0.0-9377e1dd7c4de916.jar:?]
	at lol.bai.megane.runtime.data.block.BlockData.appendServerData(BlockData.java:51) ~[megane-runtime-7.0.0-9377e1dd7c4de916.jar:?]
	at lol.bai.megane.runtime.data.block.BlockData.appendServerData(BlockData.java:23) ~[megane-runtime-7.0.0-9377e1dd7c4de916.jar:?]
	at mcp.mobius.waila.network.PacketExecutor.lambda$requestBlockEntity$2(PacketExecutor.java:98) ~[wthit-fabric-4.4.1.jar:?]
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.forEach(ObjectArrayList.java:787) ~[fastutil-8.5.6.jar:?]
	at mcp.mobius.waila.network.PacketExecutor.requestBlockEntity(PacketExecutor.java:97) ~[wthit-fabric-4.4.1.jar:?]
	at mcp.mobius.waila.fabric.FabricPacketSender.lambda$initMain$5(FabricPacketSender.java:42) ~[wthit-fabric-4.4.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[14:47:20] [Render thread/INFO]: [CHAT] Something went wrong when retrieving data for this block
```

**Comment by skylorbeck** [comment]
Can you provide what version of Minecraft you are on, what version of my mod you are using and what version of the inspector you are using?

**Comment by EnigmaticaGH** [comment]
> Can you provide what version of Minecraft you are on, what version of my mod you are using and what version of the inspector you are using?

Minecraft 1.18.1
Fabric 0.12.12
Tokenable v1.1.6
Megane 7.0.1 - Addon for WTHIT that shows stuff like inventory contents
WTHIT 4.4.1 - What the heck is that?

**Comment by skylorbeck** [comment]
Thank you. I will investigate how they pull inventories and see if I can open up a door for them.

**Comment by skylorbeck** [comment]
Fixed

**Comment by skylorbeck** [comment]
Update both Skylib and TFaS
